# Generated by Django 2.1.2 on 2018-10-23 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Measurement', models.CharField(max_length=25)),
                ('Item', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'ingredients',
                'db_table': 'Ingredients',
            },
        ),
        migrations.CreateModel(
            name='NutritionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Calories', models.IntegerField()),
                ('CarbohydrateContent', models.IntegerField()),
                ('CholesterolContent', models.IntegerField()),
                ('FatContent', models.IntegerField()),
                ('FiberContent', models.IntegerField()),
                ('ProteinContent', models.IntegerField()),
                ('SaturatedFatContent', models.IntegerField()),
                ('SodiumContent', models.IntegerField()),
                ('SugarContent', models.IntegerField()),
                ('TransFatContent', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'nutritionInfo',
                'db_table': 'NutritionInfo',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('RecipeID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('CookTime', models.DurationField()),
                ('CookingMethod', models.CharField(max_length=50)),
                ('RecipeCategory', models.CharField(max_length=50)),
                ('RecipeCuisine', models.CharField(max_length=50)),
                ('RecipeInstructions', models.TextField()),
                ('RecipeYield', models.IntegerField()),
                ('SuitableForDiet', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'recipes',
                'db_table': 'Recipe',
            },
        ),
        migrations.CreateModel(
            name='UserRecipe',
            fields=[
                ('recipe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DET_App.Recipe')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('DET_App.recipe',),
        ),
        migrations.AddField(
            model_name='recipe',
            name='Nutrition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DET_App.NutritionInfo'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='RecipeIngredients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DET_App.Ingredients'),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='NutritionInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DET_App.NutritionInfo'),
        ),
    ]
